### ISSUE TITLE
error 	addr := conn.LocalAddr().String() //:796

### ISSUE THREAD

**Issue by ultperf** [cloudwego/hertz#507]
with this error. 
go get github.com/cloudwego/hertz@develop

```
server.WithOnAccept(func(conn network.Conn) context.Context {
	addr := conn.LocalAddr().String() //:796
	log.Printf("BADIP CHECK = %s\n", addr)
	//if isBadIp(addr) {
	//	conn.Close()
	//}
	return context.Background()
}),
```				
https://github.com/cloudwego/hertz/issues/479
```
2023/01/03 19:34:32.569672 engine.go:389: [Info] HERTZ: Using network library=standard
2023/01/03 19:34:32.570042 transport.go:65: [Info] HERTZ: HERTZ: HTTP server listening on address=[::]:443
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xf6a7de]

goroutine 10 [running]:
main.main.func6({0x0?, 0x0?})
        /go/src/example.com/cloud/app/frwll/http2/frwll10.go:796 +0x1e
github.com/cloudwego/hertz/pkg/network/standard.(*transport).serve(0xc000185a00)
        /root/go/pkg/mod/github.com/cloudwego/hertz@v0.4.3-0.20230103082611-81332e6a707d/pkg/network/standard/transport.go:76 +0x2cf
github.com/cloudwego/hertz/pkg/network/standard.(*transport).ListenAndServe(0x1c29f40?, 0x120693e?)
        /root/go/pkg/mod/github.com/cloudwego/hertz@v0.4.3-0.20230103082611-81332e6a707d/pkg/network/standard/transport.go:94 +0x33
github.com/cloudwego/hertz/pkg/route.(*Engine).listenAndServe(0xc0001518c0)
        /root/go/pkg/mod/github.com/cloudwego/hertz@v0.4.3-0.20230103082611-81332e6a707d/pkg/route/engine.go:390 +0x122
github.com/cloudwego/hertz/pkg/route.(*Engine).Run(0xc0001518c0)
        /root/go/pkg/mod/github.com/cloudwego/hertz@v0.4.3-0.20230103082611-81332e6a707d/pkg/route/engine.go:357 +0x16a
github.com/cloudwego/hertz/pkg/app/server.(*Hertz).Spin.func1()
        /root/go/pkg/mod/github.com/cloudwego/hertz@v0.4.3-0.20230103082611-81332e6a707d/pkg/app/server/hertz.go:61 +0x29
created by github.com/cloudwego/hertz/pkg/app/server.(*Hertz).Spin
        /root/go/pkg/mod/github.com/cloudwego/hertz@v0.4.3-0.20230103082611-81332e6a707d/pkg/app/server/hertz.go:60 +0xca
child 1 exited with error: exit status 2
```

**Comment by welkeyever** [comment]
Thanks we will take a look.

**Comment by li-jin-gou** [comment]
```
package main

import (
	"context"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/common/hlog"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/network"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

func main() {
	h := server.Default(server.WithOnAccept(func(conn network.Conn) context.Context {
		addr := conn.LocalAddr().String()
		hlog.Info(addr)
		return context.Background()
	}))
	h.GET("/ping", func(c context.Context, ctx *app.RequestContext) {
		ctx.JSON(consts.StatusOK, utils.H{"ping": "pong"})
	})
	h.Spin()
}

```
It is not reproduced and I think it is important to fill in the content according to the issue template so as to speed up the problem solving process.

**Comment by li-jin-gou** [comment]
refer to https://github.com/cloudwego/hertz/issues/504 issue

**Comment by li-jin-gou** [comment]
> Ok I will fix this problem

I didn't notice that it was a standard library.😢
